better error handling

diff --git a/gas_price_de_ b/gas_price_de_
--- a/gas_price_de_
+++ b/gas_price_de_
@@ -58,8 +58,10 @@ GPLv2
 
 # API url
 URL="http://tanken.t-online.de/api/v1/search.xml"
+
 # maximum age of returned price
-PRICE_AGE="24"
+PRICE_AGE="48"
+
 
 # parse coordinates
 CORDS=${0##*gas_price_de_}
@@ -81,7 +83,7 @@ function query()
 {
 	# fetch file to tempfile
 	XML=$(tempfile -p gas)
-	wget --quiet "${QUERY}" -O "${XML}" || return ""
+	wget --quiet "${QUERY}" -O "${XML}" || return 1
 	echo ${XML}
 }
 
@@ -100,6 +102,9 @@ function config()
 	STREET=$(xmllint --xpath "string(/search/gasStations/gasStation/@street)" ${XML})
 	ZIP=$(xmllint --xpath "string(/search/gasStations/gasStation/@zip)" ${XML})
 	CITY=$(xmllint --xpath "string(/search/gasStations/gasStation/@city)" ${XML})
+
+	# handle errors
+	if [ -z "${NAME}" ] || [ -z "${FUEL_KIND}" ] ; then return 1 ; fi
 
 	cat <<EOF
 graph_title ${NAME}
@@ -124,23 +129,37 @@ function output()
 	# parse name
 	PRICE=$(xmllint --xpath "string(/search/gasStations/gasStation/fuels/fuel/@price)" ${XML})
 
-	echo "price.value ${PRICE}"
+	if [ -z ${PRICE} ] ; then 
+		retval=1 
+	else 
+		retval=0
+		echo "price.value ${PRICE}"
+	fi
 
 	# cleanup
 	rm "${XML}"
+	
+	return ${retval}
 }
 
+
+# fatal error
+function die()
+{
+	echo "$1"
+	exit -1
+}
 
 
 # ----------------------------------------------------------------------------
 
 case $1 in
 	"config")
-		config || die "config failed"
+		config || die "configuration failed"
 		exit
 		;;
 	*)
-		output || die "$0 failed"
+		output || die "$0 failed to query price"
 		exit
 		;;
 esac
