major design change to have multiple gas stations per graph

diff --git a/gas_price_de_ b/gas_price_de_
--- a/gas_price_de_
+++ b/gas_price_de_
@@ -7,8 +7,12 @@
                                                                                                                                               
 =head1 NAME
 
-gas_price_de_ - Graph prices of gas stations in germany with munin
-by using the http://tanken.t-online.de API
+gas_price_de_ 
+
+=head1 DESCRIPTION
+
+Graph prices of certain fuel types at gas stations within an area (defined by center 
+and radius) in germany using with munin. This uses the http://tanken.t-online.de API.
 
 =head1 PREREQUISITES
 
@@ -18,15 +22,19 @@ libxml2 (http://www.xmlsoft.org) and the "wget" utility
 
 =head1 CONFIGURATION
 
-The filename must be in this format: gas_price_de_latitude_longitude 
- latitude must be the exact latitude of the gas station
- longitude must be the exact longitude of the gas station
+ The filename must be in this format: gas_price_de_ID with
+ ID beeing a freely choosable string to allow creating 
+ multiple graphs and to set the title of the graph. ID may be empty.
 
 The following environment variables are used by this plugin
  
- fuel_type           - The type of fuel. Supported values are:
+ latitude            - center latitude of area to query   [52.527567]
+ longitude           - center longitude of area to query  [13.416131]
+ radius              - size of area (in kilometer)        [1]
+ fuel_type           - The type of fuel                   [super]
+                       Supported values are:
                           diesel
-                          super      	[default]
+                          super
                           super%20e10
                           superplus
                           autogas
@@ -36,7 +44,10 @@ The following environment variables are used by this plugin
 
 =head2 CONFIGURATION EXAMPLES
 
- [gas_price_de_52.527567_13.416131]
+ [gas_price_de_*]
+  env.latitude 52.527567
+  env.longitude 13.416131
+  env.radius 5
   env.fuel_type autogas
 
 =head1 AUTHOR
@@ -59,107 +70,130 @@ GPLv2
 # API url
 URL="http://tanken.t-online.de/api/v1/search.xml"
 
-# maximum age of returned price
+# maximum age of returned price (be sure to set this large enough
+# to avoid empty queries) Currently the API will return a single
+# most recent price per gas station/fuel type within this range
 PRICE_AGE="48"
 
 
-# parse coordinates
-CORDS=${0##*gas_price_de_}
-LAT=${CORDS%%_*}
-LNG=${CORDS##*_}
 
-if [ -z ${LAT} ] ; then LAT=52.527567 ; fi
-if [ -z ${LNG} ] ; then LNG=13.416131 ; fi
+# parse ID
+id=${0##*gas_price_de_}
 
+# default values
+latitude=${latitude:-52.527567}
+longitude=${longitude:-13.416131}
+radius=${radius:-5}
+fuel_type=${fuel_type:-super}
 
 # build query
-QUERY="${URL}?lat=${LAT}&lng=${LNG}&radius=0&price_age=${PRICE_AGE}&fuels=${fuel_type:-super}"
+QUERY="${URL}?lat=${latitude}&lng=${longitude}&radius=${radius}&price_age=${PRICE_AGE}&fuels=${fuel_type}"
+
+# array of gas station IDs
+GAS_STATIONS=()
+
+# temporary XML file
+XML=$(tempfile -p gas)
 
 
+# install trap
+trap cleanup EXIT
 
-
-# fetch XML from API
-function query()
+# clean up handler
+function cleanup()
 {
-	# fetch file to tempfile
-	XML=$(tempfile -p gas)
-	wget --quiet "${QUERY}" -O "${XML}" || return 1
-	echo ${XML}
+	if [ -e ${XML} ] ; then rm "${XML}" ; fi
 }
 
-# output configuration
-function config()
-{
-	XML=$(query) || return 1
-
-	# parse name
-	NAME=$(xmllint --xpath "string(/search/gasStations/gasStation/@name)" ${XML})
-
-	# parse fuel type
-	FUEL_KIND=$(xmllint --xpath "string(/search/gasStations/gasStation/fuels/fuel/@kind)" ${XML})
-
-	# parse address
-	STREET=$(xmllint --xpath "string(/search/gasStations/gasStation/@street)" ${XML})
-	ZIP=$(xmllint --xpath "string(/search/gasStations/gasStation/@zip)" ${XML})
-	CITY=$(xmllint --xpath "string(/search/gasStations/gasStation/@city)" ${XML})
-
-	# handle errors
-	if [ -z "${NAME}" ] || [ -z "${FUEL_KIND}" ] ; then return 1 ; fi
-
-	cat <<EOF
-graph_title ${NAME}
-graph_category fuelprices
-graph_vlabel Euro
-graph_info Prices for ${FUEL_KIND} at ${NAME} (${STREET} - ${ZIP} - ${CITY})
-price.label ${FUEL_KIND}
-EOF
-	print_warning price
-	print_critical price
-
-	# cleanup
-	rm "${XML}"
-}
-
-
-# output the last known price
-function output()
-{
-	XML=$(query) || return 1
-
-	# parse name
-	PRICE=$(xmllint --xpath "string(/search/gasStations/gasStation/fuels/fuel/@price)" ${XML})
-
-	if [ -z ${PRICE} ] ; then 
-		retval=1 
-	else 
-		retval=0
-		echo "price.value ${PRICE}"
-	fi
-
-	# cleanup
-	rm "${XML}"
-	
-	return ${retval}
-}
-
-
-# fatal error
+# fatal error handler
 function die()
 {
 	echo "$1"
 	exit -1
 }
 
+# fetch XML from API
+function query()
+{
+	# fetch file to tempfile
+	wget --quiet "${QUERY}" -O "${XML}" || die "wget \"${QUERY}\" failed"
+}
+
+# build array of GAS_STATION IDs from XML
+function parseGasStations()
+{
+	# query
+	query || die "query failed"
+
+	# parse IDs from XML
+	for ident in $(xmllint --xpath "/search/gasStations/*/@ident" ${XML}) ; do
+		sid=${ident##*ident=\"}
+		sid=${sid%%\"*}
+		GAS_STATIONS[${#GAS_STATIONS[@]}]=${sid}
+	done
+
+	if [ ${#GAS_STATIONS[@]} -eq 0 ] ; then die "no gas stations found in query" ; fi
+}
+
+# output configuration
+function config()
+{
+	# build array of gas station IDs in ${GAS_STATIONS}
+	parseGasStations || die "parsing gas stations failed"
+
+cat <<EOS
+graph_title ${id:-"Fuel prices"}
+graph_category fuelprices
+graph_vlabel Euro/Liter
+graph_info Prices for ${fuel_type}, ${radius}km around ${latitude},${longitude}
+EOS
+
+	# process every gas station found
+	for sid in ${GAS_STATIONS[@]} ; do 
+		# get name
+		name=$(xmllint --xpath "string(/search/gasStations/gasStation[@ident=\"${sid}\"]/@name)" ${XML})
+		# handle errors
+		if [ -z "${name}" ] ; then die "gas station has empty name" ; fi
+
+		echo "${sid}.label ${name}"
+		
+		print_warning ${sid}
+		print_critical ${sid}
+	done
+}
+
+
+# output the last known price
+function output()
+{
+	# build array of gas station IDs in ${GAS_STATIONS}
+	parseGasStations || die "parsing gas stations failed"
+
+	# process every gas station found
+	for sid in ${GAS_STATIONS[@]} ; do 
+		# get current price
+		price=$(xmllint --xpath "string(/search/gasStations/gasStation[@ident=\"${sid}\"]/fuels/fuel/@price)" ${XML})
+
+		# handle errors
+		if [ -z "${price}" ] ; then die "no price found" ; fi
+
+		echo "${sid}.value ${price}"
+	done
+}
+
+
+
+
 
 # ----------------------------------------------------------------------------
 
 case $1 in
 	"config")
-		config || die "configuration failed"
+		config
 		exit
 		;;
 	*)
-		output || die "$0 failed to query price"
+		output
 		exit
 		;;
 esac
